add money

diff --git a/bin/dbg_ccc_flutter b/bin/dbg_ccc_flutter
--- a/bin/dbg_ccc_flutter
+++ b/bin/dbg_ccc_flutter
@@ -2,16 +2,32 @@
 
 declare clean=no
 declare release=no
+declare device=macos
 
 while [[ "${1}" != "" ]]
 do
     case "${1}" in
-        -c|--clean            ) clean=yes;   shift; ;;
-        -r|--release|--nodebug) release=yes; shift; ;;
-        -d|--debug            ) release=no;  shift; ;;
+        -c|--clean            ) clean=yes;     shift; ;;
+        -r|--release|--nodebug) release=yes;   shift; ;;
+        -d|--debug            ) release=no;    shift; ;;
+        -m|--macos            ) device=macos;  shift; ;;
+        -t|--tablet           ) device=tablet; shift; ;;
                              *) ;;
     esac
 done
+
+if [[ "${device}" == "tablet" ]]
+then
+    declare id=`tablet_id`
+    if [[ "${id}" != "" ]]
+    then
+        device="${id}"
+    else
+        fail "Can't find tablet id!"
+        flutter doctor -v
+        exit 1
+    fi
+fi
 
 if [[ "${clean}" == "yes" ]]
 then
@@ -20,7 +36,7 @@ fi
 
 if [[ "${release}" == "yes" ]]
 then
-    flutter run -d macos --release
+    flutter run -d "${device}" --release
 else
-    flutter run -d macos
+    flutter run -d "${device}"
 fi
